# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class InlineResponse2006(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'datasource': 'DataSource',
        'id': 'int',
        'message': 'str',
        'name': 'str'
    }

    attribute_map = {
        'datasource': 'datasource',
        'id': 'id',
        'message': 'message',
        'name': 'name'
    }

    def __init__(self, datasource=None, id=None, message=None, name=None, _configuration=None):  # noqa: E501
        """InlineResponse2006 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._datasource = None
        self._id = None
        self._message = None
        self._name = None
        self.discriminator = None

        self.datasource = datasource
        self.id = id
        self.message = message
        self.name = name

    @property
    def datasource(self):
        """Gets the datasource of this InlineResponse2006.  # noqa: E501


        :return: The datasource of this InlineResponse2006.  # noqa: E501
        :rtype: DataSource
        """
        return self._datasource

    @datasource.setter
    def datasource(self, datasource):
        """Sets the datasource of this InlineResponse2006.


        :param datasource: The datasource of this InlineResponse2006.  # noqa: E501
        :type: DataSource
        """
        if self._configuration.client_side_validation and datasource is None:
            raise ValueError("Invalid value for `datasource`, must not be `None`")  # noqa: E501

        self._datasource = datasource

    @property
    def id(self):
        """Gets the id of this InlineResponse2006.  # noqa: E501

        ID Identifier of the new data source.  # noqa: E501

        :return: The id of this InlineResponse2006.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2006.

        ID Identifier of the new data source.  # noqa: E501

        :param id: The id of this InlineResponse2006.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def message(self):
        """Gets the message of this InlineResponse2006.  # noqa: E501

        Message Message of the deleted dashboard.  # noqa: E501

        :return: The message of this InlineResponse2006.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this InlineResponse2006.

        Message Message of the deleted dashboard.  # noqa: E501

        :param message: The message of this InlineResponse2006.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def name(self):
        """Gets the name of this InlineResponse2006.  # noqa: E501

        Name of the new data source.  # noqa: E501

        :return: The name of this InlineResponse2006.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse2006.

        Name of the new data source.  # noqa: E501

        :param name: The name of this InlineResponse2006.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2006, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2006):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse2006):
            return True

        return self.to_dict() != other.to_dict()
