# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class InlineResponse20015(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'external_enabled': 'bool',
        'external_snapshot_name': 'str',
        'external_snapshot_url': 'str'
    }

    attribute_map = {
        'external_enabled': 'externalEnabled',
        'external_snapshot_name': 'externalSnapshotName',
        'external_snapshot_url': 'externalSnapshotURL'
    }

    def __init__(self, external_enabled=None, external_snapshot_name=None, external_snapshot_url=None, _configuration=None):  # noqa: E501
        """InlineResponse20015 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._external_enabled = None
        self._external_snapshot_name = None
        self._external_snapshot_url = None
        self.discriminator = None

        if external_enabled is not None:
            self.external_enabled = external_enabled
        if external_snapshot_name is not None:
            self.external_snapshot_name = external_snapshot_name
        if external_snapshot_url is not None:
            self.external_snapshot_url = external_snapshot_url

    @property
    def external_enabled(self):
        """Gets the external_enabled of this InlineResponse20015.  # noqa: E501


        :return: The external_enabled of this InlineResponse20015.  # noqa: E501
        :rtype: bool
        """
        return self._external_enabled

    @external_enabled.setter
    def external_enabled(self, external_enabled):
        """Sets the external_enabled of this InlineResponse20015.


        :param external_enabled: The external_enabled of this InlineResponse20015.  # noqa: E501
        :type: bool
        """

        self._external_enabled = external_enabled

    @property
    def external_snapshot_name(self):
        """Gets the external_snapshot_name of this InlineResponse20015.  # noqa: E501


        :return: The external_snapshot_name of this InlineResponse20015.  # noqa: E501
        :rtype: str
        """
        return self._external_snapshot_name

    @external_snapshot_name.setter
    def external_snapshot_name(self, external_snapshot_name):
        """Sets the external_snapshot_name of this InlineResponse20015.


        :param external_snapshot_name: The external_snapshot_name of this InlineResponse20015.  # noqa: E501
        :type: str
        """

        self._external_snapshot_name = external_snapshot_name

    @property
    def external_snapshot_url(self):
        """Gets the external_snapshot_url of this InlineResponse20015.  # noqa: E501


        :return: The external_snapshot_url of this InlineResponse20015.  # noqa: E501
        :rtype: str
        """
        return self._external_snapshot_url

    @external_snapshot_url.setter
    def external_snapshot_url(self, external_snapshot_url):
        """Sets the external_snapshot_url of this InlineResponse20015.


        :param external_snapshot_url: The external_snapshot_url of this InlineResponse20015.  # noqa: E501
        :type: str
        """

        self._external_snapshot_url = external_snapshot_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20015, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20015):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20015):
            return True

        return self.to_dict() != other.to_dict()
