# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Permission(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action': 'str',
        'created': 'datetime',
        'scope': 'str',
        'updated': 'datetime'
    }

    attribute_map = {
        'action': 'action',
        'created': 'created',
        'scope': 'scope',
        'updated': 'updated'
    }

    def __init__(self, action=None, created=None, scope=None, updated=None, _configuration=None):  # noqa: E501
        """Permission - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._action = None
        self._created = None
        self._scope = None
        self._updated = None
        self.discriminator = None

        if action is not None:
            self.action = action
        if created is not None:
            self.created = created
        if scope is not None:
            self.scope = scope
        if updated is not None:
            self.updated = updated

    @property
    def action(self):
        """Gets the action of this Permission.  # noqa: E501


        :return: The action of this Permission.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this Permission.


        :param action: The action of this Permission.  # noqa: E501
        :type: str
        """

        self._action = action

    @property
    def created(self):
        """Gets the created of this Permission.  # noqa: E501


        :return: The created of this Permission.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Permission.


        :param created: The created of this Permission.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def scope(self):
        """Gets the scope of this Permission.  # noqa: E501


        :return: The scope of this Permission.  # noqa: E501
        :rtype: str
        """
        return self._scope

    @scope.setter
    def scope(self, scope):
        """Sets the scope of this Permission.


        :param scope: The scope of this Permission.  # noqa: E501
        :type: str
        """

        self._scope = scope

    @property
    def updated(self):
        """Gets the updated of this Permission.  # noqa: E501


        :return: The updated of this Permission.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this Permission.


        :param updated: The updated of this Permission.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Permission, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Permission):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Permission):
            return True

        return self.to_dict() != other.to_dict()
