# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class PostGraphiteAnnotationsCmd(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'str',
        'tags': 'object',
        'what': 'str',
        'when': 'int'
    }

    attribute_map = {
        'data': 'data',
        'tags': 'tags',
        'what': 'what',
        'when': 'when'
    }

    def __init__(self, data=None, tags=None, what=None, when=None, _configuration=None):  # noqa: E501
        """PostGraphiteAnnotationsCmd - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._data = None
        self._tags = None
        self._what = None
        self._when = None
        self.discriminator = None

        if data is not None:
            self.data = data
        if tags is not None:
            self.tags = tags
        if what is not None:
            self.what = what
        if when is not None:
            self.when = when

    @property
    def data(self):
        """Gets the data of this PostGraphiteAnnotationsCmd.  # noqa: E501


        :return: The data of this PostGraphiteAnnotationsCmd.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this PostGraphiteAnnotationsCmd.


        :param data: The data of this PostGraphiteAnnotationsCmd.  # noqa: E501
        :type: str
        """

        self._data = data

    @property
    def tags(self):
        """Gets the tags of this PostGraphiteAnnotationsCmd.  # noqa: E501


        :return: The tags of this PostGraphiteAnnotationsCmd.  # noqa: E501
        :rtype: object
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this PostGraphiteAnnotationsCmd.


        :param tags: The tags of this PostGraphiteAnnotationsCmd.  # noqa: E501
        :type: object
        """

        self._tags = tags

    @property
    def what(self):
        """Gets the what of this PostGraphiteAnnotationsCmd.  # noqa: E501


        :return: The what of this PostGraphiteAnnotationsCmd.  # noqa: E501
        :rtype: str
        """
        return self._what

    @what.setter
    def what(self, what):
        """Sets the what of this PostGraphiteAnnotationsCmd.


        :param what: The what of this PostGraphiteAnnotationsCmd.  # noqa: E501
        :type: str
        """

        self._what = what

    @property
    def when(self):
        """Gets the when of this PostGraphiteAnnotationsCmd.  # noqa: E501


        :return: The when of this PostGraphiteAnnotationsCmd.  # noqa: E501
        :rtype: int
        """
        return self._when

    @when.setter
    def when(self, when):
        """Sets the when of this PostGraphiteAnnotationsCmd.


        :param when: The when of this PostGraphiteAnnotationsCmd.  # noqa: E501
        :type: int
        """

        self._when = when

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostGraphiteAnnotationsCmd, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostGraphiteAnnotationsCmd):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PostGraphiteAnnotationsCmd):
            return True

        return self.to_dict() != other.to_dict()
