# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class SlackField(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'short': 'bool',
        'title': 'str',
        'value': 'str'
    }

    attribute_map = {
        'short': 'short',
        'title': 'title',
        'value': 'value'
    }

    def __init__(self, short=None, title=None, value=None, _configuration=None):  # noqa: E501
        """SlackField - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._short = None
        self._title = None
        self._value = None
        self.discriminator = None

        if short is not None:
            self.short = short
        if title is not None:
            self.title = title
        if value is not None:
            self.value = value

    @property
    def short(self):
        """Gets the short of this SlackField.  # noqa: E501


        :return: The short of this SlackField.  # noqa: E501
        :rtype: bool
        """
        return self._short

    @short.setter
    def short(self, short):
        """Sets the short of this SlackField.


        :param short: The short of this SlackField.  # noqa: E501
        :type: bool
        """

        self._short = short

    @property
    def title(self):
        """Gets the title of this SlackField.  # noqa: E501


        :return: The title of this SlackField.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this SlackField.


        :param title: The title of this SlackField.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def value(self):
        """Gets the value of this SlackField.  # noqa: E501


        :return: The value of this SlackField.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this SlackField.


        :param value: The value of this SlackField.  # noqa: E501
        :type: str
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SlackField, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SlackField):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SlackField):
            return True

        return self.to_dict() != other.to_dict()
